### PR TITLE
Micro improvements 

### PR DESCRIPTION
**Pull request by sosauce**
Hi ! I saw you did this with AI, which wasn't that bad actually 😯 

I made some small improvements:

Minor UI improvements (Added some rounded corners where there wasn't as it seems some part of the UI was rounded and some wasn't)
Added a favicon (little icon next to tab title!, feel free to remove it !)
Separated css and script in separate files (for convenience and readability)

That's all :D

### CODE REVIEW

**Comment by nubesurrealista** [comment]
👀 Thank u very much!!

**Comment by nubesurrealista** [comment]
@sosauce Sorry to draw your attention but, I'm trying to understand why the page is not working correctly, the loading of information does not happen as before, it stays in an eternal loop, and the themes no longer work 😞 but I have checked, and in theory it should not affect the loading of posts, could you check if there is something that could interfere? I'm trying to find out on my side but I'm very inexperienced lol

Should I change something?

**Comment by sosauce** [comment]
Oh let me see, because it was working for me 🤔

**Comment by sosauce** [comment]
Okayyy so, you should try copying all the JavaScript code (from script.js) in between the <script> and </script> tags in the HTML file, if it doesn't work, I will revert all the changes 😧

**Comment by nubesurrealista** [comment]
> you should try copying all the JavaScript code (from script.js) in between the <script> and </script> tags in the HTML file

Now it works! Thank u very much!!!

**Pull request merged**
